# SPDX-FileCopyrightText: © 2019-2026 Nadim Kobeissi <nadim@symbolic.software>
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "verifpal"
version = "1.0.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Verifpal language support for the Zed editor."
repository = "https://github.com/symbolicsoft/verifpal-zed"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7"

[profile.release]
opt-level = "s"
lto = true
strip = true
