# SPDX-FileCopyrightText: © 2019-2026 Nadim Kobeissi <nadim@symbolic.software>
# SPDX-License-Identifier: GPL-3.0-only

id = "verifpal"
name = "Verifpal"
description = "Verifpal language support: highlighting, the language server built into the Verifpal binary, snippets and tasks."
version = "1.0.0"
schema_version = 1
authors = ["Nadim Kobeissi <nadim@symbolic.software>"]
repository = "https://github.com/symbolicsoft/verifpal-zed"

snippets = ["./snippets/verifpal.json"]

[grammars.verifpal]
repository = "file:///Users/nadim/Code/symbolic/verifpal/verifpal-zed"
rev = "2fd2b86b8428db5f5e1fe3e6a0a12357f47a6e53"
path = "tree-sitter-verifpal"

[language_servers.verifpal]
name = "Verifpal"
languages = ["Verifpal"]
